version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "trunk"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "UTC"
    labels:
      - "dependencies"
    open-pull-requests-limit: 9
    pull-request-branch-name:
      separator: "-"
