stages:
  - vet
  - test
  - build
  - upload
  - release

variables:
  PACKAGE_VERSION: "0.0.14"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/release/${PACKAGE_VERSION}"
  PACKAGE_NAME: "${CI_PROJECT_NAME}-v${PACKAGE_VERSION}"

.nodejs: &nodejs
  image: node:12.22.1
  cache:
    paths:
      - node_modules
  before_script:
    - node --version
    - npm --version
    - make setup

# vet {{{
check:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - cp config.json{.sample,}
    - make vet:check
  except:
    - tags

tslint:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make vet:lint:ts
  except:
    - tags

stylint:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make vet:lint:styl
  except:
    - tags
# }}}

# test {{{
test:
  stage: test
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - cp config.json.sample config.json
    - make coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  except:
    - tags
# }}}

# build {{{
build-debug:
  stage: build
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - cp config.json.sample config.json
    - make build:debug

build-release:
  stage: build
  <<: *nodejs
  variables:
    NODE_ENV: production
  script:
    - cp config.json.sample config.json
    - make build:release
    - |
      sed -i "s/index.\(\(css\|js\)\)/index.min.\1?v=$(date +%s)/" \
        dst/index.html
    - tar czvf dst.tar.gz dst
  artifacts:
    paths:
      - dst
      - dst.tar.gz
    expire_in: 3 days
  only:
    - release@eloquentlog/eloquentlog-web-console
    - tags@eloquentlog/eloquentlog-web-console
# }}}

# publish {{{
upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
        --upload-file dst.tar.gz $PACKAGE_REGISTRY_URL/$PACKAGE_NAME.tar.gz
  dependencies:
    - build-release
  only:
    - tags@eloquentlog/eloquentlog-web-console

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create \
        --name "Release ${CI_COMMIT_TAG}" \
        --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${PACKAGE_NAME}.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}.tar.gz\"}"
  dependencies:
    - upload
  only:
    - tags@eloquentlog/eloquentlog-web-console
# }}}
