stages:
  - vet
  - test

.nodejs: &nodejs
  image: node:12.16.1
  cache:
    paths:
      - node_modules
  before_script:
    - node --version
    - npm --version
    - npm install
  except:
    - tags

lint-typescript:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make verify:lint:ts

lint-stylus:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make verify:lint:styl

test:
  stage: test
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make test
