stages:
  - verify
  - test
  - build
  - deploy

.gentoo: &gentoo
  image: registry.gitlab.com/grauwoelfchen/portolan/gentoo-amd64-nomultilib:latest

.nodejs: &nodejs
  image: node:12.16.1
  cache:
    paths:
      - node_modules
  before_script:
    - node --version
    - npm --version
    - npm install

.cloud-sdk:
  - &cloud-sdk
    mkdir -p .tool;
    cd .tool;
    if [ ! -d "../.cloud-sdk" ]; then
      mkdir -p ../.cloud-sdk;
      curl -O $CLOUD_SDK_BASE_URL/$CLOUD_SDK_FILENAME;
      echo "${CLOUD_SDK_CHECKSUM}" "" ./$CLOUD_SDK_FILENAME | sha256sum -c -;
      cp $CLOUD_SDK_FILENAME ../.cloud-sdk/;
    else
      cp ../.cloud-sdk/$CLOUD_SDK_FILENAME .;
    fi;
    tar zxf $CLOUD_SDK_FILENAME;
    ./$CLOUD_SDK_ARTIFACT/install.sh
      --command-completion=false
      --path-update=false
      --usage-reporting=false
      --rc-path=/dev/null
      --override-components beta core
      --quiet >$CLOUD_SDK_ARTIFACT/install.log 2>&1;
    cd ../

verify-typescript:
  stage: verify
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make verify:lint:ts
  except:
    - tags

verify-stylus:
  stage: verify
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make verify:lint:styl
  except:
    - tags

test:
  stage: test
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make test
  except:
    - tags

build-development:
  stage: build
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - cp config.json.sample config.json
    - make build:development

build-production:
  stage: build
  <<: *nodejs
  variables:
    NODE_ENV: production
  script:
    - cp $CONFIG_JSON_FILE config.json
    - make build:production
  artifacts:
    paths:
      - dst
    expire_in: 3 days
  only:
    - release@eloquentlog/eloquentlog-web-console
    - master@eloquentlog/eloquentlog-web-console
    - tags

release:
  stage: deploy
  <<: *gentoo
  variables:
    CLOUD_SDK_BASE_URL: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads
    CLOUD_SDK_CHECKSUM: 4773911e9f8fb7fe3b915e1f24ebe957436474253688820a9f2990d7399bd3b8
    CLOUD_SDK_ARTIFACT: google-cloud-sdk
    CLOUD_SDK_FILENAME: ${CLOUD_SDK_ARTIFACT}-301.0.0-linux-x86_64.tar.gz
    # set as secret variables
    # GCP_CREDENTIAL_JSON: /path/to/credential.json
    # GCP_CLOUD_STORAGE_BUCKET_NAME: bucket_name
    # GCP_PROJECT_ID: eloquentlog
  before_script:
    - *cloud-sdk
  script:
    - . .tool/$CLOUD_SDK_ARTIFACT/path.bash.inc; make deploy
  only:
    - release@eloquentlog/eloquentlog-web-console
    - tags@eloquentlog/eloquentlog-web-console
